version: "2"
run:
  concurrency: 4
  go: 1.24.6
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goprintffuncname
    - gosec
    - govet
    - iface
    - importas
    - inamedparam
    - ineffassign
    - maintidx
    - makezero
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - staticcheck
    - tagliatelle
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead, see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
    errcheck:
      check-type-assertions: true
    errorlint:
      errorf: false
    exhaustive:
      default-signifies-exhaustive: true
      explicit-exhaustive-switch: true
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G108
    govet:
      disable:
        - fieldalignment
        - slog
      enable-all: true
      settings:
        shadow:
          strict: true
    iface:
      enable:
        - identical
        - unused
        - opaque
    nestif:
      min-complexity: 5
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: unused-parameter
          disabled: true
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    tagliatelle:
      case:
        use-field-name: true
    testifylint:
      enable-all: true
      disable:
        - require-error
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - maintidx
          - maligned
          - musttag
          - revive
        path: _test\.go
      - path: internal/model/ports.go
        text: ^yaml.+$
      - linters:
          - govet
        text: '^shadow: declaration of "err" shadows declaration.+'
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(capuchinator)
    goimports:
      local-prefixes:
        - capuchinator
    golines:
      max-len: 160
      reformat-tags: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
