version: 2

project_name: capuchinator

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'main.appVersion={{.Version}}'
    binary: capuchinator
    main: ./main.go

archives:
  - formats: [tar.gz]
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}" # capuchinator_v1.0.0_linux_amd64.tar.gz

changelog:
  use: git
  filters:
    # Исключаем merge коммиты
    exclude:
      - "^Merge"
      - "^merge"
